[package]
name = "music_rescue"
version = "0.3.1"
edition = "2024"

[dependencies]
audiotags = "0.5"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
