[package]
name = "music_rescue"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
